# Generated by Django 3.2.4 on 2021-06-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
    ]
